### ISSUE TITLE
老哥 能加下联系方式或者啥的吗 群聊也行  

### ISSUE THREAD

**Issue by sxc1234** [junhaideng/baidu-zhidao#2]
正在获取第 1 页的问题id
Traceback (most recent call last):
  File "/www/wwwroot/baidu-zhidao-main/main.py", line 9, in <module>
    questions = get_questions()
  File "/www/wwwroot/baidu-zhidao-main/question.py", line 60, in get_questions
    soup = BeautifulSoup(resp.text, 'lxml')
  File "/www/wwwroot/baidu-zhidao-main/9df62e693988eb4e1e1444ece0578579_venv/lib/python3.9/site-packages/bs4/__init__.py", line 245, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

我用宝塔上的python项目管理器跑的  版本 3.9.7  但会出现这样的问题

**Comment by junhaideng** [comment]
没安装库
```
pip install lxml
```
