### ISSUE TITLE
老哥 麻烦了  有空 帮我看一看   拜托了

### ISSUE THREAD

**Issue by sxc1234** [junhaideng/baidu-zhidao#3]
正在获取第 18 页的问题id
正在获取第 19 页的问题id
正在获取第 20 页的问题id
Traceback (most recent call last):
  File "/usr/local/ql/repo/junhaideng_baidu-zhidao/main.py", line 24, in <module>
    content = get_answer(desc)
  File "/usr/local/ql/repo/junhaideng_baidu-zhidao/answer.py", line 49, in get_answer
    href = answer.attrs["href"]
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by junhaideng** [comment]
这里是因为没有搜索到答案，使用最新代码
